project:
  type: book

book:
  title: "Data Science Across Disciplines"
  image: media/IM939_logo.png
  author: 
    - name: "Cagatay Turkay"
      affiliation: University of Warwick (CIM)
      affiliation-url: http://warwick.ac.uk/cim
      orcid: 0000-0001-6788-251X
    - name: "Carlos Cámara"
      url: http://carloscamara.es/en
      affiliation: University of Warwick (CIM)
      affiliation-url: http://warwick.ac.uk/cim
      orcid: 0000-0002-9378-0549
    - name: "James Tripp"
      affiliation:  University of Warwick (IDG)
      orcid: 0000-0003-2471-3411
  date: "8/14/2023"
  favicon: media/CIM_logo.png
  cover-image: media/IM939_logo.png
  twitter-card: true
  site-url: https://warwickcim.github.io/IM939_handbook_quarto/
  repo-url: https://github.com/WarwickCIM/IM939_handbook_quarto
  repo-actions: [edit, issue]
  downloads: [pdf, epub]

  chapters:
    - index.qmd
    - part: "Sessions"
      chapters:
        - content/sessions/session-01.md
        - summary.qmd
    - part: content/labs/lab-01.md
      chapters:
        - "content/labs/week1/IM939 Lab 1 - Part 1.ipynb"
  appendices:
    - content/jupyterbook-demo/notebooks.ipynb
    - references.qmd

execute: 
  enabled: true
  freeze: true

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-copy: true
  #pdf:
    #documentclass: scrreprt

editor: visual

