project:
  type: book

book:
  title: "IM939_handbook_quarto"
  author: "Norah Jones"
  date: "8/14/2023"
  chapters:
    - index.qmd
    - intro.qmd
    - "content/labs/week1/IM939 Lab 1 - Part 1.ipynb"
    - content/jupyterbook-demo/notebooks.ipynb
    - summary.qmd
    - references.qmd

execute: 
  enabled: true
  freeze: true

bibliography: references.bib

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: visual

