---
jupyter: python3
---

# Data Science Across Disciplines {.unnumbered}


::: {.callout-warning}
This page is still a stub
:::

This is a small sample book to give you a feel for how book content is
structured.
It shows off a few of the major file types, as well as some sample content.
It does not go in-depth into any particular topic - check out [the Jupyter Book documentation](https://jupyterbook.org) for more information.


## Table of contents

Currently, this book is replicating the existing structure consiting of one repo for sessions (Cagatay's repo) and another one for labs' content (James) by mapping each repo into two different sections: Sessions and Labs.

::: {.callout-tip}

### Proposed table of contents

However, I suspect, though, that if we proceed with the handbook, the structure should be based on units/weeks, and every unit should contain both, the session and the labs

```
- 1: Introduction, Historical Perspectives & Basic Concepts
    - Session
    - Labs
- 2: Thinking data
    - Session (probably on the root?)
    - Labs
...
```
:::


